### ISSUE TITLE
How to solve it？？？？？

### ISSUE THREAD

**Issue by czalt1028** [biubug6/Pytorch_Retinaface#141]
Traceback (most recent call last):
  File "test_widerface.py", line 107, in <module>
    im_size_min = np.min(im_shape[0:2])
  File "<__array_function__ internals>", line 6, in amin
  File "D:\AI\anaconda3-5.3.1\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 2831, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "D:\AI\anaconda3-5.3.1\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

How to solve it？？？？？

**Comment by imistyrain** [comment]
图片路径不对，数据没读进来，形状信息为空，取下标挂掉
