### ISSUE TITLE
can you export onnx?

### ISSUE THREAD

**Issue by wangpupanjing** [biubug6/Pytorch_Retinaface#2]
can you export onnx?

**Comment by biubug6** [comment]
> can you export onnx?

It's easy. I'll provide it later .

**Comment by piotr-anyvision** [comment]
@biubug6 If you could do it, that would be amazing!

**Comment by SnowRipple** [comment]
@biubug6  Do you have any timetable for the onnx model please?

**Comment by biubug6** [comment]
@SnowRipple @wangpupanjing  So sorry to have kept you waiting. Now I provide script "convert_to_onnx.py" to export onnx.

**Comment by oiabtt** [comment]
@biubug6 I got an error.
`==> Exporting model to ONNX format at 'FaceDetector.onnx'
Traceback (most recent call last):
  File "convert_to_onnx.py", line 97, in <module>
    input_names=input_names, output_names=output_names)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
    _retain_param_name=_retain_param_name)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 313, in _export
    _retain_param_name)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 248, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 167, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 535, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 122, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 122, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/myuser/.conda/envs/retinaface_pytorch/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 78, in _parse_arg
    raise RuntimeError("ONNX symbolic expected a constant value in the trace")
RuntimeError: ONNX symbolic expected a constant value in the trace`

pytorch 1.3.0
then I update to 1.3.1, error still occuerd

**Comment by SnowRipple** [comment]
I think I had the same error, the problem was with onnx not pytorch, just updated onnx (pytorch can have different onnx version) ;)

**Comment by oiabtt** [comment]
@SnowRipple  have you solve this problem? I think the problem raised by some bugs of pytorch.onnx

**Comment by SnowRipple** [comment]
Yes, but it was a while ago so I don't remember specifics - it is known problem with onnx, but there was simple fix - try google;)

**Comment by oiabtt** [comment]
@SnowRipple but in fact that we only use torch.onnx in this code, and we did not use onnx. that is to say it has nothing to do with onnx, because we did not import it. this is a toturial by onnx(https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb), when conver pytorch model to onnx model, it use torch.onnx just like the code in  Pytorch_Retinaface.

**Comment by 121649982** [comment]
can you tell me how to load .onnx model with tensor RT , thank you very much.


I load the model like this ：
	std::string dataDirs = "E:/gc/Pytorch_Retinaface-master";
	std::vector<std::string> dir;
	dir.push_back(dataDirs);
    auto parsed = parser->parseFromFile(
        locateFile("FaceDetector.onnx", dir).c_str(), static_cast<int>(gLogger.getReportableSeverity()));
    if (!parsed)
    {
        return false;
    }


but,I get this errors:

sorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:10] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:10] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:10] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:10] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:10] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:11] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/07/2020-19:19:11] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 106 [Upsample]:
ERROR: builtin_op_importers.cpp:3240 In function importUpsample:
[8] Assertion failed: scales_input.is_weights()

**Comment by xsacha** [comment]
I think torch2trt is better than going pytorch -> onnx -> tensorrt

**Comment by zzxaijs** [comment]
[01/07 / 2020-19：19：11] [W] [TRT] onnx2trt_utils.cpp：198：您的ONNX模型是使用INT64权重生成的，而TensorRT本身不支持INT64。尝试转换为INT32。
解析节点号106 [Upsample]时：
错误：builtin_op_importers.cpp：3240在函数importUpsample中：
[8]断言失败：scales_input.is_weights（）,同样的这个错怎么解决

**Comment by denisvmedyantsev** [comment]
I faced the problem of the `pytorch -> onnx -> tensorrt` approach as above. I used [simplifier](https://github.com/daquexian/onnx-simplifier), it helped, but I found a new problem: the output is different for different batch size for the trt engine. Fix the interpolation instead of using the simplifier in https://github.com/biubug6/Pytorch_Retinaface/blob/b984b4b775b2c4dced95c1eadd195a5c7d32a60b/models/net.py#L89 and https://github.com/biubug6/Pytorch_Retinaface/blob/b984b4b775b2c4dced95c1eadd195a5c7d32a60b/models/net.py#L93 It helped. Just cast size to int, eg. `F.interpolate(output3, size=[output2.size(2), output2.size(3)], mode="nearest")` => `F.interpolate(output3, size=(int(output2.size(2)), int(output2.size(3))), mode="nearest")`
