### ISSUE TITLE
ValueError: 'box_overlaps.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Coderx7** [biubug6/Pytorch_Retinaface#71]
Hi @biubug6 ,
Thank you very much for your great work here really appreciate it. 
I wanted to run the widerface evaluation and followed your instruction which was doing : 

##### before evaluating ....

````
python3 setup.py build_ext --inplace
````
and doing so results in the aforementioned error. here is  the stacktrace : 
```
PS D:\Codes\Pytorch_Retinaface> python .\widerface_evaluate\setup.py build_ext --inplace
Traceback (most recent call last):
  File ".\widerface_evaluate\setup.py", line 13, in <module>
    setup(ext_modules=cythonize([package]))
  File "C:\Users\User\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
    aliases=aliases)
  File "C:\Users\User\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Users\User\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
    raise ValueError(error_msg)
ValueError: 'box_overlaps.pyx' doesn't match any files
```

Would you kindly help me understand whats going wrong here and how to fix it? 
Its really appreciated

**Comment by Coderx7** [comment]
Oh OK! I found the casue, I had to first cd into the widerface_evaluation and run that command there!
